### ISSUE TITLE
UltiEconomy and UltiWorlds fail to load: stale ABI against AbstractDataEntity / Spring context, broken since 2026-02-18

### ISSUE THREAD

**Issue by wisdommen** [UltiKits/UltiTools-Reborn#351]
Real-machine UAT of #349 on Paper 1.21.4 / Java 21 loaded **14 of 16** framework modules.
`UltiEconomy` and `UltiWorlds` fail at enable time with `NoSuchMethodError` against framework APIs
that no longer exist. The break is **not** caused by #349 or by the 6.3.0 milestone — it dates to
2026-02-18 and is already present in the released 6.2.5 artifact.

## Failure signatures

```
java.lang.NoSuchMethodError:
  'com.ultikits.ultitools.abstracts.AbstractDataEntity com.ultikits.ultitools.interfaces.Query.first()'
      -> UltiWorlds (and the same signature inside UltiEconomy's chain)

java.lang.NoSuchMethodError:
  'org.springframework.context.annotation.AnnotationConfigApplicationContext
   com.ultikits.plugins.economy.UltiEconomy.getContext()'
      -> UltiEconomy
```

## Dating the break

| Check | Result |
|---|---|
| `Query.first()` in the released `UltiTools-API-6.2.5.jar` (`javap`) | `public abstract T first();` on `Query<T extends BaseDataEntity<String>>` — the `AbstractDataEntity` return is already gone |
| When the bound changed | `43f55ea`, 2026-02-18, `refactor!: replace AbstractDataEntity with BaseDataEntity<String> across all framework APIs` |
| Spring `AnnotationConfigApplicationContext` in framework `src/main` on `alpha` | 0 hits (positive control: `SimpleContainer`, 13 hits). The shaded JAR does not bundle Spring. |
| Files #349 touched matching `Query` or `Spring` | 0 (positive control: #349 changed 19 files) |

So both modules have been incompatible since 2026-02-18, through the whole 6.2.x line.

## What this means

Two of sixteen modules cannot load against current `alpha`, and against the released 6.2.5. Any
real-machine UAT from here on will report a blocked machine gate until they are rebuilt, which
makes the UAT signal harder to read for every subsequent phase — a pre-existing failure that is
always present is indistinguishable at a glance from a new one.

## Suggested fix

Rebuild both modules against the current framework ABI, in their own repositories:

- **`UltiWorlds`** — `Query.first()` now returns `T` bound by `BaseDataEntity<String>`. Migrate the
  entity off the deprecated `AbstractDataEntity`; note `getDataOperator` is bounded
  `<T extends BaseDataEntity<String>>`, so `AbstractDataEntity` is a compile error there, not a warning.
- **`UltiEconomy`** — `getContext()` returning a Spring `AnnotationConfigApplicationContext` predates
  the removal of Spring from the framework. It should return the framework's own container type.

## UAT evidence

`machine-verdict.json`, `cold-start-and-probes.log` and `class-histogram.txt` from the #349 cold-start
run are on the maintainer's UAT host. Same run confirmed the parts #349 is about are clean:
all 16 main classes have exactly one live instance, 98 config files unchanged (0 content, 0 mtime),
0 `@AliasFor` errors, 13 command help topics registered.

**Comment by wisdommen** [comment]
**Status update from the 6.3.0 pre-release acceptance pass (2026-09-04): the code defect described here is fixed, but the fix is stranded on an unmerged branch with no pull request open.**

## Both modules now load and function

Measured on the acceptance server (Paper 1.21.4, framework `6.3.0-SNAPSHOT`, jar `74039aaf06b9`):

```
[16:29:13] [PlaceholderAPI] Successfully registered internal expansion: ultieconomy [1.0.0]
[16:29:14] [UltiTools] [UltiWorlds] worlds_enabled
```

No `NoSuchMethodError` for either, and their commands were exercised for real:

| Module | acceptance results |
|---|---|
| UltiEconomy | 28 pass / 4 fail |
| UltiWorlds | 9 pass / 25 fail / 2 blocked |

The failures are unrelated to loading — almost all are #389 (raw i18n keys) plus the module-specific defects filed separately (UltiWorlds#10–#13, UltiEconomy#10).

## The stale ABI is gone from both artifacts and both sources

Deployed jars (rebuilt 2026-09-04 10:18), read with `strings` rather than grep-on-binary:

| jar | `AbstractDataEntity` | `springframework` | control: `BaseDataEntity` |
|---|---|---|---|
| `UltiEconomy-2.0.0.jar` | 0 | 0 | 8 |
| `UltiWorlds-1.0.0.jar` | 0 | 0 | 8 |

Sources agree — 0 files matching either stale symbol in each module's `src/main`, with `BaseDataEntity` found in 3 and 2 files respectively as the control.

## What is not done

Both fixes sit on `gsd/phase-09-module-readiness` in their respective repositories:

- committed and pushed (`git status` clean, 0 commits ahead of upstream)
- **not merged into `master`** in either repo (`git branch -r --merged origin/master` does not contain the branch)
- **no pull request open** for it in either repo — UltiEconomy has none; UltiWorlds' only open PRs are two Dependabot bumps

So anyone installing the published `UltiEconomy` or `UltiWorlds` still gets the version this issue describes. The remaining work is a merge and a release, not a code change.

Not opening those pull requests here: that branch belongs to a separate workstream whose completeness I have not reviewed, and merging it is a scope decision rather than a finding. Flagging it because a 6.3.0 release that ships while these stay unmerged leaves both modules broken for users, which is the situation this issue was filed about.

## Note on the dating in the original report

The original analysis stands — the break dates to `43f55ea` (2026-02-18) and was present in released 6.2.5, not introduced by #349 or by the 6.3.0 milestone. Nothing above contradicts that; only the current state has moved.

**Comment by wisdommen** [comment]
**Closed with re-verified evidence (Phase 15, plan 15-20) — both modules now load cleanly on the default branch.**

- **Current HEAD:** `b9a5ddbd1b0e4aeab62d62d4cbf83f3a91288ff3` (branch `alpha`)
- **Fixing commits:** `82241887` (UltiEconomy, "feat(09-08): pin UltiEconomy to 6.3.0-SNAPSHOT and close its branch/line coverage gap") and `35bdb58` (UltiWorlds, "feat(09-06): pin UltiTools-API to 6.3.0-SNAPSHOT, add live jacoco coverage gate") — both confirmed ancestors of each module's current `master` HEAD (`91ac5fec19`, `969ae5a265` respectively), not stranded on an unmerged branch as the 2026-09-04 comment above described.
- **Proving command and output, re-run at this HEAD:**

  ```
  $ grep -rn "AbstractDataEntity\|AnnotationConfigApplicationContext" UltiEconomy/src/main UltiWorlds/src/main
  # 0 hits

  $ grep -rn "extends BaseDataEntity" UltiEconomy/src/main/java | head -3
  CurrencyBalanceEntity.java:14:public class CurrencyBalanceEntity extends BaseDataEntity<String> {
  TreasuryEntity.java:14:public class TreasuryEntity extends BaseDataEntity<String> {
  PlayerAccountEntity.java:18:public class PlayerAccountEntity extends BaseDataEntity<String> {
  ```

  Both modules' `pom.xml` are pinned to `UltiTools-API 6.3.0-SNAPSHOT`. The generation-counter/Spring-context ABI break this issue described no longer exists in either module's source.

Register entry: `/home/wisdomme/servers/evidence/phase-15/15-DEFECT-REGISTER.md`, row `UltiTools-Reborn | #351` (Phase 15 local evidence, bucket a — already resolved).
